import {
    fetchArticleData,
    fetchAttributeGroupData,
    fetchBannerData,
    fetchBrandData,
    fetchCatalogData,
    fetchCategoryData,
    fetchColorData,
    fetchFilialData,
    fetchGalleryData,
    fetchMasterImagesData,
    fetchMenuData,
    fetchPartnerData,
    fetchProductBannerData,
    fetchProductData,
    fetchRoomData,
    fetchSettingData,
    fetchWeightData,
} from './fetch/main';
import {
    fetchProductAttributeRelationData,
    fetchProductCategoryRelationData,
    fetchProductColorRelationData,
    fetchProductWeightRelationData,
} from './fetch/relation';
import {
    fetchArticleTranslateData,
    fetchAttributeGroupTranslateData,
    fetchBrandTranslateData,
    fetchCatalogTranslateData,
    fetchCategoryTranslateData,
    fetchColorTranslateData,
    fetchFilialTranslateData,
    fetchMenuTranslateData,
    fetchProductBannerTranslateData,
    fetchProductTranslateData,
    fetchRoomTranslateData,
    fetchSettingTranslateData,
} from './fetch/translate';

import {
    CategoryTranslation,
    FilialTranslation,
    MenuTranslation,
    SettingTranslation,
    CatalogTranslation,
} from './translate'

export {
    fetchArticleData,
    fetchAttributeGroupData,
    fetchBannerData,
    fetchBrandData,
    fetchCatalogData,
    fetchCategoryData,
    fetchColorData,
    fetchFilialData,
    fetchGalleryData,
    fetchMasterImagesData,
    fetchMenuData,
    fetchPartnerData,
    fetchProductBannerData,
    fetchProductData,
    fetchRoomData,
    fetchSettingData,
    fetchWeightData,

    fetchProductAttributeRelationData,
    fetchProductCategoryRelationData,
    fetchProductColorRelationData,
    fetchProductWeightRelationData,

    fetchArticleTranslateData,
    fetchAttributeGroupTranslateData,
    fetchBrandTranslateData,
    fetchCatalogTranslateData,
    fetchCategoryTranslateData,
    fetchColorTranslateData,
    fetchFilialTranslateData,
    fetchMenuTranslateData,
    fetchProductBannerTranslateData,
    fetchProductTranslateData,
    fetchRoomTranslateData,
    fetchSettingTranslateData,

    CategoryTranslation,
    FilialTranslation,
    MenuTranslation,
    SettingTranslation,
    CatalogTranslation,
}